name: Mint NFT

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email address of the user'
        required: true
        type: string

jobs:
  mint-nft:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Mint NFT
        env:
          # API_URL: https://api.mintology.app/v1/${{ secrets.MINTOLOGY_PROJECT_ID }}/mint
          # API_KEY: ${{ secrets.MINTOLOGY_API_KEY }}
          # PREMINT_ID: ${{ secrets.MINTOLOGY_PREMINT_ID }}
          API_URL: https://api.mintology.app/v1/01J57V9TV05AH9EBBH3S1HH4VV/mint  #temp
          API_KEY: MDFKNTdUQ0Y3NUtERVhYRFM4VlJURjEzS0s6NmJkZTViN2RlOTFlN2MyNzQ3ZGJmOWFiZmJlMDIxYmU3MzAwZGIxZDM2N2Q1Yjk2MmE5ODNmOTBhYjg3MjQ2OA #temp
          PREMINT_ID: 'icp'  #temp
          EMAIL: ${{ github.event.inputs.email }}

        run: |
          curl -X POST "$API_URL" \
            -H "Authorization: Bearer ${{ secrets.API }}" \
            -H "accept: application/json" \
            -H "content-type: application/json" \
            -H "API-Key: $API_KEY" \
            -d '{
                  "email": "'"$EMAIL"'",
                  "premint_id": "'"$PREMINT_ID"'"
                }'
